version: '3.8'

services:
  # خدمة قاعدة البيانات
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # خدمة الـ Node.js (تطبيقك)
  app:
    build: .
    ports:
      - "8000:3000"
    depends_on:
      db:
        condition: service_healthy # التأكد أن الداتابيز اشتغلت قبل التطبيق